name = "livesnaps"
compatibility_date = "2026-08-30"
compatibility_flags = ["nodejs_compat"]
main = "./src/worker.ts"

[vars]
CONVEX_URL = "https://nautical-bobcat-280.convex.cloud"

[build]
command = "bun run build"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "none"
